"""Install agent8s as an ordinary macOS application (~/Applications/agent8s.app).

The bundle is only a launcher: its executable starts the window (`agent8s-desktop --app`) from the
service's private runtime, so double-clicking, Launchpad and Spotlight work without a terminal. The
window attaches to the background service (see service.py); the app starts that service itself when
it is not running.
"""
from __future__ import annotations

import plistlib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional

from . import service

APP_NAME = "agent8s"
BUNDLE_ID = "com.agent8s.desktop.app"
ICON_PNG = Path(__file__).parent / "assets" / "icon-1024.png"
ICONSET_SIZES = (16, 32, 128, 256, 512)  # each also as @2x


class AppError(RuntimeError):
    pass


def default_dir() -> Path:
    return Path.home() / "Applications"


def app_path(dest_dir: Optional[Path] = None) -> Path:
    return (dest_dir or default_dir()) / f"{APP_NAME}.app"


def info_plist() -> bytes:
    return plistlib.dumps(
        {
            "CFBundleName": APP_NAME,
            "CFBundleDisplayName": APP_NAME,
            "CFBundleIdentifier": BUNDLE_ID,
            "CFBundleExecutable": APP_NAME,
            "CFBundleIconFile": APP_NAME,
            "CFBundlePackageType": "APPL",
            "CFBundleShortVersionString": "0.1.0",
            "CFBundleVersion": "1",
            "LSMinimumSystemVersion": "11.0",
            "LSApplicationCategoryType": "public.app-category.developer-tools",
            "NSHighResolutionCapable": True,
        }
    )


def launcher_script(runtime_exe: Path, log_file: Path) -> str:
    return (
        "#!/bin/bash\n"
        "# agent8s launcher (generated by `agent8s-desktop --install-app`; no terminal involved)\n"
        f'exec "{runtime_exe}" --app >> "{log_file}" 2>&1\n'
    )


def build_icns(png: Path, out: Path) -> None:
    """PNG -> .icns with the macOS tools (sips + iconutil)."""
    with tempfile.TemporaryDirectory() as tmp:
        iconset = Path(tmp) / f"{APP_NAME}.iconset"
        iconset.mkdir()
        for size in ICONSET_SIZES:
            for scale in (1, 2):
                pixels = size * scale
                name = f"icon_{size}x{size}{'@2x' if scale == 2 else ''}.png"
                result = subprocess.run(
                    ["sips", "-z", str(pixels), str(pixels), str(png), "--out", str(iconset / name)],
                    capture_output=True, text=True,
                )
                if result.returncode != 0:
                    raise AppError(f"sips не смог изменить размер иконки: {result.stderr.strip()}")
        result = subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(out)], capture_output=True, text=True)
        if result.returncode != 0:
            raise AppError(f"iconutil не собрал иконку: {result.stderr.strip()}")


def install_app(runtime_exe: Path, dest_dir: Optional[Path] = None, log_file: Optional[Path] = None) -> Path:
    if sys.platform != "darwin":
        raise AppError("Приложение собирается только на macOS.")
    if not ICON_PNG.exists():
        raise AppError(f"Нет файла иконки {ICON_PNG}")
    bundle = app_path(dest_dir)
    # Build next to the target and swap, so a failed build never destroys a working app.
    staging = bundle.with_name(f".{bundle.name}.new")
    shutil.rmtree(staging, ignore_errors=True)
    (staging / "Contents" / "MacOS").mkdir(parents=True)
    (staging / "Contents" / "Resources").mkdir()

    (staging / "Contents" / "Info.plist").write_bytes(info_plist())
    launcher = staging / "Contents" / "MacOS" / APP_NAME
    launcher.write_text(launcher_script(runtime_exe, log_file or service.LOG_DIR / "app.log"))
    launcher.chmod(0o755)
    build_icns(ICON_PNG, staging / "Contents" / "Resources" / f"{APP_NAME}.icns")

    # An ad-hoc signature gives the bundle a stable identity (best effort: it works unsigned too).
    subprocess.run(["codesign", "--force", "--sign", "-", str(staging)], capture_output=True)

    bundle.parent.mkdir(parents=True, exist_ok=True)
    shutil.rmtree(bundle, ignore_errors=True)
    staging.rename(bundle)
    return bundle


def uninstall_app(dest_dir: Optional[Path] = None) -> bool:
    bundle = app_path(dest_dir)
    existed = bundle.exists()
    shutil.rmtree(bundle, ignore_errors=True)
    return existed


def cli(do_install: bool, do_uninstall: bool) -> int:
    try:
        if do_install:
            for line in service.install():  # the app is a window on this service: set both up
                print(line)
            bundle = install_app(service.RUNTIME_DIR / "bin" / "agent8s-desktop")
            print(f"Приложение установлено: {bundle}")
            print("Откройте его из Launchpad или Spotlight («agent8s»); в Dock можно закрепить через контекстное меню.")
        elif do_uninstall:
            print("Приложение удалено." if uninstall_app() else "Приложение не было установлено.")
            print("Фоновый сервис остался (отключить: --uninstall-service).")
        return 0
    except (AppError, service.ServiceError) as exc:
        print(f"Ошибка: {exc}", file=sys.stderr)
        return 1
